# Generated by Django 3.2 on 2021-05-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='date_birth',
            field=models.DateField(default='2019-01-01'),
            preserve_default=False,
        ),
    ]
