# Generated by Django 3.2 on 2021-05-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dossier_date_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=2),
            preserve_default=False,
        ),
    ]
