# Generated by Django 3.2 on 2021-05-05 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dossier_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warcraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('military_area', models.CharField(max_length=20)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='war_crfts', to='accounts.dossier')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=20)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='accounts.dossier')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=20)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='accounts.dossier')),
            ],
        ),
    ]
